{% set version = "2.6.2" %}

package:
  name: varlociraptor
  version: {{ version }}

build:
  number: 0
  # Skipping macOS builds due to unresolved linking error:
  #  Undefined symbols for architecture x86_64:
  #    "_SSLCopyALPNProtocols", referenced from:
  #        _sectransp_connect_step2 in libcurl_sys-c372a728cc50d01a.rlib(sectransp.o)
  #    "_SSLSetALPNProtocols", referenced from:
  #        _sectransp_connect_common in libcurl_sys-c372a728cc50d01a.rlib(sectransp.o)
  skip: True  # [osx]

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: e196896f284960b6594215f2a5e0006d870a95c51f2616043ba065349b75f77b

requirements:
  build:
    - rust >=1.30
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - gsl
    - libcblas
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
    - blis
  run:
    - blis

test:
  commands:
    - varlociraptor -h

about:
  home: https://varlociraptor.github.io
  license: GPLv3
  license_family: GPL
  summary: Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control.
