{% set name = "mobidic-mpa" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "567dea4a7d17701ee670e3a31cd3295ab04bd4a0f32a3532f6095b9b98647f5b"

build:
  number: 0
  entry_points:
    - mpa_main=mobidic_mpa:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python
    - pyvcf ==0.6.8

test:
  imports:
    - mobidic_mpa
  commands:
    - mpa --version

about:
  home: "https://neuro-2.iurc.montp.inserm.fr/mpaweb/"
  license: "MIT"
  license_family: "MIT"
  summary: "MPA: MoBiDiC Prioritization Algorithm"
  dev_url: "https://github.com/mobidic/MPA"

extra:
  recipe-maintainers:
    - Char-Al
  identifiers:
    - doi:10.1016/j.jmoldx.2018.03.009
